### ISSUE TITLE
mismatched tag: line 4, column 2

### ISSUE THREAD

**Issue by imbraintl** [DPO-Group/DPO_Odoo#2]
When click Paynow at domain.com/shop/payment the below error will be generated

Server Error
We are not able to process your payment.
mismatched tag: line 4, column 2

**Comment by kalungia** [comment]
Same here

**Comment by bruce-atkinson** [comment]
@imbraintl @kalungia, please kindly submit your bug report, including the platform and steps to reproduce on https://dpogroup.com/contact-us/.

**Comment by imbraintl** [comment]
Good day,
The provided link does support screenshot/media attachment.
Please see the screenshot below for the bug
[image: image.png]

**Comment by bruce-atkinson** [comment]
Hi @imbraintl,

Once a ticket has been lodged and assigned, the support team will be able to receive attachments within the body of the email reply.

**Comment by imbraintl** [comment]
Hi @appinlet 
Thank you, I did that.
